apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::846533034013:role/eksctl-eksctl-demo-nodegroup-ng-2-NodeInstanceRole-YH8H6W0JWQ0F
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::846533034013:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-29T00:10:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1499"
  uid: 2efae2c1-aaa0-49e5-bd48-527d785e0dd0
